- name: Create Resource Group 
  hosts:  all
  tasks:


    - name: Create a resource group
      azure_rm_resourcegroup:
        name: RG-VST-CSP-DEV-ASA-500
        location: westus
        tags:
            testing: testing
            delete: never