- name: Create Resource Group 
  hosts:  all
  tasks:


    - name: Create a resource group
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: westus
        tags:
            testing: testing
            delete: never