- name: Variable Playbook 
  hosts:  all
  vars:
    service_name: PlugPlay
  tasks:
    - name: Restart Service 
      win_service:
        name: "{{ service_name }}"
        state: restarted
      register: service_output

    - name: Print Output
      debug:
        var:  service_output.state


    - name: Print Hostname
      debug:
        var:  ansible_hostname